name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Set Condition
        id: condition
        run: |
          if [[ "${{ github.event_name }}" == 'issues' ]]; then
              echo "username=${{ github.event.issue.user.login }}" >> $GITHUB_ENV
          else
              echo "username=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
          fi
      - name: Greet User
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message:  "Thank you @${{ env.username }} for bringing up this issue to help enhance our project even further! We'll review it soon. ğŸ™Œâ¤ï¸"
          pr-message: "Thank you for opening a pull request @${{ env.username }}. We'll will review it as soon as possible ğŸ™Œâ¤ï¸"
